### ISSUE TITLE
Reproducibility of analyses

### ISSUE THREAD

**Issue by dhimmel** [idrdex/star-django#20]
Several things are worth considering for analysis reproducibility.

+ each analysis saves and reports which samples were cases and which were controls
+ [*not neccesary*] based on the case and control assignments, each analysis receives a hash
+ analyses have versions. 'Rerun' creates a new version rather than overwriting
+ analyses belong to users. I shouldn't be able to modify another user's analysis. But I should be able to fork

One final and slightly unrelated request, is that analysis-specific tagging stats are provided. These stats would show which users contributed how much to the tagging.

**Comment by Suor** [comment]
On reproducibility. This is harder than just remembering samples. Actual series matrices change over time as well as probes.

On rerun. There is "Run a copy" which creates a new version. "Rerun" is for cases when you don't want to keep current version. It's very useful for debugging purposes, but it could be removed later of we stop needing it.

Also, please don't gather several features into single issue, this makes discussing and processing it harder.

**Comment by dhimmel** [comment]
> please don't gather several features into single issue

I combined these issues because, I thought they are all related -- decisions regarding one affect the others. Will try to be more targeted in the future.

> On reproducibility. This is harder than just remembering samples. Actual series matrices change over time as well as probes.

Interesting -- I still think the solution will still be a combination of timestamping, checksums, versioning, and users.

Check out [Tribe](http://tribe.greenelab.com/#/use/list) which is a crowdsourced gene set collection platform. Each gene set, called a collection, is created by a user. Whenever, the user updates that collection, a new version is created. I can fork another user's collection, but I cannot modify the original.

I see that these changes may be difficult to engineer, but without users and versioning I think you will run into problems as the site grows.

**Comment by Suor** [comment]
Checksums can't be used for reproducability and timestamps can only be used if we can get data for any time in a past, which is untrue both for GEO and our own architecture. To make analysis reproducible we will need to store all the data it uses as input and then reuse it on subsequent run. Both are significant changes to current implementation.

Unlike tribe we don't control changes to most of our input data.

**Comment by dhimmel** [comment]
What about providing a table with the series and sample_ids for cases and controls? Here is a shortened version of what the table for multiple sclerosis would look like:

series | sample_id | class
---|---|---
GSE17449 | 81990 | case
GSE17449 | 81991 | case
GSE17449 | 144981 | control
GSE17449 | 144982 | control
GSE23832 | 144977 | case
GSE23832 | 144978 | case
GSE23832 | 144977 | control
GSE23832 | 144978 | control

Knowing which studies and samples went into an analysis is crucial from an academic viewpoint. Even if this table is insufficient to entirely reproduce an analysis, it's an important start. Additionally, this information will help users understand their results and diagnose problems.

**Comment by Suor** [comment]
This could be done fairly easily.

**Comment by idrdex** [comment]
A lot of this functionality is in the API in order to query more detailed annotations ad perform finer scale analysis.  I like the above table for each analysis on the website though.  Maybe we can provide the user the annotation data frame as a parameter for each analysis much like we show the case, control, and modifier queries, and min samples now.

**Comment by Suor** [comment]
Here are my thoughts on reproducability:
- the only way to achive perfect one is to save all input data,
- if some piece of input could be determined by reference (e.g. GSE number) then that could be used instead,
- unforturnately series matrices change with time so GSE+GPL can't be used as reference, GSE+GPL+date can't be used as reference as long as we only use GEO ftp as only datasource. This is because they don't store old versions of series matrices. Storing our copies and refering to them will work.
- analysis dataframe can also change as annotations are updated, so we need to store that too.
- I don't know if platform probes could change, if they do then we need to store them too. The table we use is not updated now, but I wonder if source data on ftp could change.

So this will be implemented in 3 steps:
- store analysis dataframe, make it available on website and via API.
- store series matrices, make registry GSE+GPL+date -> URL to deduplicate their storage, add easy to use matrices access functions, add transparent local file cache, make them available via API.
- somehow deal with platform probes. At least make them accesssible via API.

I will start with step 1, among other things this will bring us table @dhimmel showed above. Step 2 will follow as needed (e.g. API calls like adding analysis automatically can go first). Step 3 will depend on whether platform probes can change, can they @idrdex?

**Comment by idrdex** [comment]
Let's chat tonight. Although they might change, the vast majority of sample data will be stable soon after deposit. Platforms are standardized somewhat. So they should not change.

**Comment by Suor** [comment]
Added source frame table [here](http://dev.stargeo.io/analysis/218/frame/). Dataframes are automatically uploaded to S3 for each new analysis. Old analyses could be rerun to get that.

Next things:
- make it downloadable,
- add convenient way to access it from star-api.

**Comment by idrdex** [comment]
This is really nice. And sets a data freeze for papers as supplemental data.
