### ISSUE TITLE
Changed genes refered in platform file for same probe

### ISSUE THREAD

**Issue by Suor** [idrdex/star-django#45]
The example would be GPL6288. `kc` are keys changed, `savedf` was loaded from `platform_probe` table, `newf` was extracted from current family file using GB_LIST (accession) column.

```
ipdb> kc
[u'2199', u'26722', u'36224', u'39963', u'4907', u'5795', u'21700', u'25034', u'29553', u'32871', u'19404']
ipdb> len(kc)
11
ipdb> savedf.loc[kc]
       mygene_entrez    mygene_sym  probe
probe                                    
2199           57698      KIAA1598   2199
26722      100130700  LOC100130700  26722
36224         645090       CXorf30  36224
39963         645090       CXorf30  39963
4907       100288695        LIMS3L   4907
5795       100128176  LOC100128176   5795
21700         140768         SMCR2  21700
25034         387977     NOVA1-AS1  25034
29553      101927067  LOC101927067  29553
32871      101928036  LOC101928036  32871
19404         196483        FAM86A  19404
ipdb> newf.loc[kc]
       mygene_entrez mygene_sym  probe
probe                                 
2199           57698      SHTN1   2199
26722      100130700  TP53TG3HP  26722
36224         286464     CFAP47  36224
39963         286464     CFAP47  39963
4907       100288695      LIMS4   4907
5795       100128176    UST-AS1   5795
21700      105371564      SMCR2  21700
25034      102725045  NOVA1-AS1  25034
29553      101927067  LINC01607  29553
32871      101928036     HRAT17  32871
19404         196483    EEF2KMT  19404
```

**Comment by idrdex** [comment]
These are all fine and expected due to the variable nature of genome annotation.  These genes are all relatively new and as such identifiers/names may change but they become stable over time.  It is not a big deal because of that fact as the bulk of genes were discovered long ago with stable names / identifiers and thus represented across multiple platforms.  All these genes will be on only a few platforms as they are relatively new genes.

Take probe 2199 whose mygene_sym changed from KIAA1598 to SHTN1 and mygene_entrez remained stable.  KIAA named symbols are transient by definition until a more permanent biologically relevant symbol is assigned.  Here's a list of all aliases for SHTN1: http://www.genecards.org/cgi-bin/carddisp.pl?gene=SHTN1#aliases_descriptions and clearly KIAA1598 is a prior alias.  The same applies to any LOC, CXorf, or FAM named symbols which are all transient until a stable symbol is assigned.

Similarly, mygene_entrez identifiers can also change.  For probe 21700 for SMCR2, for instance, Gene ID: 140768 was discontinued on 5-Apr-2015 and replaced with Gene ID: 105371564 (https://www.ncbi.nlm.nih.gov/gene/?term=140768) as shown in your annotations changes.

**Comment by Suor** [comment]
So should we update probes?

**Comment by Suor** [comment]
I think I can also improve probe matching algorithm significantly, so there would be many more probe-gene pairs for some platforms.

**Comment by idrdex** [comment]
Might as well update probes. For the case of non - specific probes that bit duplicate genes, either we assign all  gene names or none. I think none is most conservative so let's go with that. Thx.

**Comment by Suor** [comment]
Ok, summary - update probes, skip dups.
