### ISSUE TITLE
Delete original annotations

### ISSUE THREAD

**Issue by Suor** [idrdex/star-django#68]
by @idrdex 
> We need a way to delete original annotations. In fact the idea of annotation vs validation are relatively arbitrary given we have canonical annotations now. Moderators should be able to delete any annotation irrespective of the order (i.e. Including the original annotation). This feature may be a good reason to refactor the backend to remove the duplicate tables of annotation vs validation.

**Comment by Suor** [comment]
I still don't understand why this is needed. If original annotation is wrong then 2 validations will match and become canonical. No need to delete anything.

I agree that we can move away from separation of annotations and validations though. We already did this is API.

**Comment by idrdex** [comment]
If the original annotation doesn't apply to begin with, then there is currently no way to delete it. This has become a more serious problem now we can post annotations by API. See http://stargeo.org/annotations/6431/samples/ where a careless regex matched Age incorrectly resulting in a mis-annotation of Age. Manually adding a second annotation of regex NONE by the web interface to correct the original API mis-post is kludgy not to mention misleading to count as an annotation since the original series_annotation should not exist in the first place.

**Comment by Suor** [comment]
So you want canonical annotation to also be removed in this case?

**Comment by idrdex** [comment]
Correct. A canonical annotation with no matching annotations is pretty useless. So it should just be removed or marked as such on deletion.

**Comment by idrdex** [comment]
Why not just mark canonical as deleted but leave in place? If somebody else annotates the same series with the same tag, just resurrect the canonical record.  Once internal identifiers are assigned, I think we should never change them.

**Comment by Suor** [comment]
Ok, I see. Marking canonical deleted is ok. 

Uniting original annotations and validations make total sense but not a fast thing to do. Is it worth to make deletion first or just go for rehaul?

**Comment by idrdex** [comment]
We definitely need 'delete' asap, but I'd just go for rehaul. Easier to code against and analyze one table. Especially now API access is live.

**Comment by Suor** [comment]
This is done. 

Rehaul is done as well: now we have `raw_series_annotation` and `raw_sample_annotation` for user entered data, `series_annotation` and `sample_annotation` for canonical annotations. Old tables are still there for time being, but would be removed in the future.
